/*
 * Platform Utility function 
 *
 * Other functions needed by anyone using the platform
 *
 * API version: 5.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse2001 struct {
	Namespace string `json:"namespace"`
	Description string `json:"description,omitempty"`
	Active bool `json:"active"`
	AllowedIdentifierCountInReferenceGroup int32 `json:"allowed_identifier_count_in_reference_group,omitempty"`
	AllowedActiveIdentifierCountInReferenceGroup int32 `json:"allowed_active_identifier_count_in_reference_group,omitempty"`
}
