/*
 * Platform Utility function 
 *
 * Other functions needed by anyone using the platform
 *
 * API version: 5.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RequestsStatus struct {
	RequestId string `json:"request_id"`
	RequesterNodeId string `json:"requester_node_id"`
	Mode int32 `json:"mode"`
	RequestMessageHash string `json:"request_message_hash"`
	MinIal float64 `json:"min_ial"`
	MinAal float64 `json:"min_aal"`
	MinIdp int32 `json:"min_idp"`
	IdpIdList []string `json:"idp_id_list"`
	ResponseList []RequestsStatusResponseList `json:"response_list"`
	DataRequestList []RequestsStatusDataRequestList `json:"data_request_list"`
	RequestTimeout int32 `json:"request_timeout"`
	TimedOut bool `json:"timed_out"`
	Closed bool `json:"closed"`
	RequestType string `json:"request_type,omitempty"`
	Status string `json:"status"`
	// <CHAIN_ID>:<BLOCK_HEIGHT>
	CreationBlockHeight string `json:"creation_block_height"`
}
