/*
 * Platform Utility function 
 *
 * Other functions needed by anyone using the platform
 *
 * API version: 5.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type OutboundPrivateMessageInner struct {
	Message string `json:"message"`
	Direction string `json:"direction"`
	Destinations []interface{} `json:"destinations"`
	Timestamp float64 `json:"timestamp"`
}
