/*
 * Platform Utility function 
 *
 * Other functions needed by anyone using the platform
 *
 * API version: 5.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RequestsStatusResponseList1 struct {
	AsId string `json:"as_id"`
	Signed bool `json:"signed,omitempty"`
	ReceivedData bool `json:"received_data,omitempty"`
	ErrorCode float64 `json:"error_code,omitempty"`
}
