/*
 * Platform Utility function 
 *
 * Other functions needed by anyone using the platform
 *
 * API version: 5.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ErrorError struct {
	Code float64 `json:"code,omitempty"`
	Message string `json:"message,omitempty"`
}
