/*
 * Platform Utility function 
 *
 * Other functions needed by anyone using the platform
 *
 * API version: 5.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RequestsStatusResponseList struct {
	Ial float64 `json:"ial,omitempty"`
	Aal float64 `json:"aal,omitempty"`
	Status string `json:"status,omitempty"`
	ErrorCode float64 `json:"error_code,omitempty"`
	Signature string `json:"signature,omitempty"`
	IdpId string `json:"idp_id"`
	// Whether response signature is correct
	ValidSignature bool `json:"valid_signature,omitempty"`
	// Whether response IAL is less than or equal to identity IAL
	ValidIal bool `json:"valid_ial,omitempty"`
}
