/*
 * Platform Utility function 
 *
 * Other functions needed by anyone using the platform
 *
 * API version: 5.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type IdpForIdentity struct {
	NodeId string `json:"node_id"`
	NodeName string `json:"node_name"`
	MaxIal float64 `json:"max_ial"`
	MaxAal float64 `json:"max_aal"`
	OnTheFlySupport bool `json:"on_the_fly_support,omitempty"`
	// IdP supported request message MIME types
	SupportedRequestMessageDataUrlTypeList []string `json:"supported_request_message_data_url_type_list"`
	Agent bool `json:"agent"`
	ModeList []int32 `json:"mode_list"`
	Ial float64 `json:"ial"`
	Lial bool `json:"lial,omitempty"`
	Laal bool `json:"laal,omitempty"`
}
