/*
 * Platform Utility function 
 *
 * Other functions needed by anyone using the platform
 *
 * API version: 5.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RequestsStatusDataRequestList struct {
	ServiceId string `json:"service_id"`
	AsIdList []string `json:"as_id_list"`
	MinAs int32 `json:"min_as"`
	RequestParamsHash string `json:"request_params_hash"`
	ResponseList []RequestsStatusResponseList1 `json:"response_list,omitempty"`
}
