/*
 * Platform Utility function 
 *
 * Other functions needed by anyone using the platform
 *
 * API version: 5.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PriceCeiling struct {
	ServiceId string `json:"service_id"`
	PriceCeilingByCurrencyList []PriceCeilingPriceCeilingByCurrencyList `json:"price_ceiling_by_currency_list"`
}
