/*
 * Platform Utility function 
 *
 * Other functions needed by anyone using the platform
 *
 * API version: 5.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type As struct {
	NodeId string `json:"node_id"`
	NodeName string `json:"node_name"`
	MinIal float64 `json:"min_ial"`
	MinAal float64 `json:"min_aal"`
	SupportedNamespaceList []string `json:"supported_namespace_list"`
}
