/*
 * Platform Utility function 
 *
 * Other functions needed by anyone using the platform
 *
 * API version: 5.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InboundPrivateMessageInner struct {
	Message *interface{} `json:"message"`
	Direction string `json:"direction"`
	Source *interface{} `json:"source"`
	Signature string `json:"signature"`
	SignatureForProxy string `json:"signature_for_proxy,omitempty"`
	Timestamp float64 `json:"timestamp"`
}
