/*
 * Platform Utility function 
 *
 * Other functions needed by anyone using the platform
 *
 * API version: 5.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PriceMinEffectiveDatetimeDelay struct {
	DurationSecond float64 `json:"duration_second"`
}
